"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Modal;
exports.OrderModal = OrderModal;
exports.ReservationModal = ReservationModal;
var jsx_runtime_1 = require("react/jsx-runtime");
var react_1 = require("motion/react");
var lucide_react_1 = require("lucide-react");
var react_2 = __importDefault(require("react"));
var LanguageContext_1 = require("../contexts/LanguageContext");
function Modal(_a) {
    var isOpen = _a.isOpen, onClose = _a.onClose, title = _a.title, children = _a.children, _b = _a.className, className = _b === void 0 ? "bg-[var(--color-tactical)]" : _b;
    return ((0, jsx_runtime_1.jsx)(react_1.AnimatePresence, { children: isOpen && ((0, jsx_runtime_1.jsxs)("div", { className: "fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6", children: [(0, jsx_runtime_1.jsx)(react_1.motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, onClick: onClose, className: "absolute inset-0 bg-black/80 backdrop-blur-sm" }), (0, jsx_runtime_1.jsxs)(react_1.motion.div, { initial: { opacity: 0, scale: 0.95, y: 20 }, animate: { opacity: 1, scale: 1, y: 0 }, exit: { opacity: 0, scale: 0.95, y: 20 }, className: "relative w-[clamp(280px,90vw,672px)] max-h-[90vh] flex flex-col border border-white/10 rounded-sm shadow-2xl overflow-hidden ".concat(className), children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between p-6 border-b border-white/10 bg-black/40", children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-2xl font-display uppercase italic text-white", children: title }), (0, jsx_runtime_1.jsx)("button", { onClick: onClose, className: "p-2 text-gray-300 hover:text-white transition-colors", children: (0, jsx_runtime_1.jsx)(lucide_react_1.X, { className: "w-6 h-6" }) })] }), (0, jsx_runtime_1.jsx)("div", { className: "p-8 max-h-[80vh] overflow-y-auto bg-black/20", children: children })] })] })) }));
}
function OrderModal(_a) {
    var isOpen = _a.isOpen, onClose = _a.onClose;
    var t = (0, LanguageContext_1.useLanguage)().t;
    return ((0, jsx_runtime_1.jsx)(Modal, { isOpen: isOpen, onClose: onClose, title: t('modal.orderTitle'), className: "bg-[#1A1A1A] !rounded-2xl !border-[var(--color-safety)]/30 !shadow-[0_0_40px_rgba(251,188,5,0.15)]", children: (0, jsx_runtime_1.jsxs)("div", { className: "text-center relative z-10", children: [(0, jsx_runtime_1.jsx)("div", { className: "absolute inset-0 bg-gradient-to-b from-[var(--color-safety)]/5 to-transparent pointer-events-none -m-8 p-8 h-[200px] opacity-50" }), (0, jsx_runtime_1.jsxs)("div", { className: "relative z-10", children: [(0, jsx_runtime_1.jsx)("div", { className: "w-20 h-20 bg-[var(--color-safety)]/10 rounded-full flex items-center justify-center mx-auto mb-6 border border-[var(--color-safety)]/20", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Phone, { className: "w-10 h-10 text-[var(--color-safety)]" }) }), (0, jsx_runtime_1.jsxs)("p", { className: "text-xl text-gray-300 mb-8 leading-relaxed font-medium", children: [t('modal.orderDesc1'), (0, jsx_runtime_1.jsx)("span", { className: "text-[var(--color-safety)] font-black", children: t('modal.orderDesc2') }), t('modal.orderDesc3')] }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-4", children: [(0, jsx_runtime_1.jsxs)("a", { href: "tel:+421911650032", className: "flex items-center justify-center gap-3 w-full bg-[var(--color-safety)] text-black py-6 rounded-xl font-display text-3xl font-bold tracking-widest hover:bg-yellow-400 transition-all shadow-xl uppercase italic", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Phone, { className: "w-8 h-8" }), "+421 911 650 032"] }), (0, jsx_runtime_1.jsx)("p", { className: "text-gray-400 text-sm uppercase tracking-widest font-bold", children: t('modal.weAreHere') })] })] })] }) }));
}
function ReservationModal(_a) {
    var isOpen = _a.isOpen, onClose = _a.onClose;
    var t = (0, LanguageContext_1.useLanguage)().t;
    return ((0, jsx_runtime_1.jsx)(Modal, { isOpen: isOpen, onClose: onClose, title: t('modal.resTitle'), className: "bg-[#1A1A1A] !rounded-2xl !border-[var(--color-safety)]/30 !shadow-[0_0_40px_rgba(251,188,5,0.15)]", children: (0, jsx_runtime_1.jsxs)("div", { className: "text-center relative z-10", children: [(0, jsx_runtime_1.jsx)("div", { className: "absolute inset-0 bg-gradient-to-b from-[var(--color-safety)]/5 to-transparent pointer-events-none -m-8 p-8 h-[200px] opacity-50" }), (0, jsx_runtime_1.jsxs)("div", { className: "relative z-10", children: [(0, jsx_runtime_1.jsx)("div", { className: "w-20 h-20 bg-[var(--color-safety)]/10 rounded-full flex items-center justify-center mx-auto mb-6 border border-[var(--color-safety)]/20", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Phone, { className: "w-10 h-10 text-[var(--color-safety)]" }) }), (0, jsx_runtime_1.jsxs)("p", { className: "text-xl text-gray-300 mb-8 leading-relaxed font-medium", children: [t('modal.resDesc1'), (0, jsx_runtime_1.jsx)("br", {}), t('modal.resDesc2')] }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-4", children: [(0, jsx_runtime_1.jsxs)("a", { href: "tel:+421911650032", className: "flex items-center justify-center gap-3 w-full bg-[var(--color-safety)] text-black py-6 rounded-xl font-display text-3xl font-bold tracking-widest hover:bg-yellow-400 transition-all shadow-xl uppercase italic", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Phone, { className: "w-8 h-8" }), "+421 911 650 032"] }), (0, jsx_runtime_1.jsx)("p", { className: "text-gray-400 text-sm uppercase tracking-widest font-bold", children: t('modal.weAreHere') })] })] })] }) }));
}
